import { env } from 'cloudflare:workers';import { getRequestSession } from '../../../../lib/auth';import { deterministicShuffle,jsonAnswers,jsonArray,jsonNumberMap } from '../../../../lib/candidate-store';import { parseSettings } from '../../../../lib/assessment-store';import { ensureResultSchema } from '../../../../lib/result-store';import { visualFromStorage } from '../../../../lib/structured-visual';
export async function GET(request:Request){
  const user=await getRequestSession(request);if(!user)return Response.json({error:'Sign in required.'},{status:401});await ensureResultSchema();const attemptId=new URL(request.url).searchParams.get('attemptId');if(!attemptId)return Response.json({error:'Attempt is required.'},{status:400});
  const attempt=await env.DB.prepare(`SELECT t.*,a.title,a.description,a.duration_seconds,a.settings_json,a.status AS assessment_status,a.question_count,a.total_marks FROM attempts t JOIN assessments a ON a.id=t.assessment_id WHERE t.id=? AND t.user_id=?`).bind(attemptId,user.sub).first<Record<string,unknown>>();if(!attempt)return Response.json({error:'Attempt not found.'},{status:404});
  const released=attempt.assessment_status==='results_released';if(attempt.status!=='started')return Response.json({attemptId,status:attempt.status,submittedAt:attempt.submitted_at,score:released?attempt.score:null,maxScore:released?attempt.max_score:null,resultsReleased:released});
  const now=Math.floor(Date.now()/1000);
  const rows=await env.DB.prepare(`SELECT id,position,type,prompt,passage,options_json,image_key,visual_kind,visual_spec_json,visual_alt_text,marks,negative_marks,tag,topic,subtopic,difficulty FROM questions WHERE assessment_id=? AND is_active=1`).bind(attempt.assessment_id).all<Record<string,unknown>>();
  const byId=new Map(rows.results.map((row)=>[String(row.id),row]));const order=jsonArray(attempt.question_order_json);const settings=parseSettings(String(attempt.settings_json||'{}'));
  const questions=order.map((id)=>byId.get(id)).filter(Boolean).map((row)=>{const options=jsonArray(row!.options_json);return {id:row!.id,type:row!.type,prompt:row!.prompt,passage:row!.passage,options:settings.shuffleOptions?deterministicShuffle(options,`${attempt.shuffle_seed}:${row!.id}`):options,hasImage:Boolean(row!.image_key),visual:visualFromStorage(row!.visual_kind,row!.visual_spec_json,row!.visual_alt_text),marks:row!.marks,negativeMarks:row!.negative_marks,tag:row!.tag,topic:row!.topic,subtopic:row!.subtopic,difficulty:row!.difficulty};});
  return Response.json({attemptId,status:'started',assessment:{id:attempt.assessment_id,title:attempt.title,description:attempt.description,durationSeconds:attempt.duration_seconds,questionCount:attempt.question_count,totalMarks:attempt.total_marks,settings},questions,answers:jsonAnswers(attempt.answers_json),marked:jsonArray(attempt.marked_json),timeSpent:jsonNumberMap(attempt.time_spent_json),answerVersion:Number(attempt.answer_version),tabSwitches:Number(attempt.tab_switches),serverNow:now,expiresAt:Number(attempt.expires_at)});
}
